# This workflow will install text2term, run tests, and upload test coverage results to codecov

name: CI Tests
run-name: CI Testing on ${{ github.event_name }}

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov wheel
    - name: Install text2term
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest --cov=./text2term test --cov-branch --cov-report=xml
    - name: Debug- confirm coverage.xml file
      run: find . -name coverage.xml
    - name: Upload test coverage report to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./text2term/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
