name: Upload TestPyPI
run-name: Upload ${{ github.event.release.tag_name }} to TestPyPI

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine sdist wheel build
    - name: Install text2term
      run: |
        pip install -e .
    - name: Build distribution
      run: |
        python -m build --sdist --wheel --no-isolation --outdir dist/ .
    - name: Upload to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
